### ISSUE TITLE
Load the corpus/preprocessed data

### ISSUE THREAD

**Issue by DolanDack** [microsoft/methods2test#2]
Hi, I am new to the transformers and LLM, trying to fine-tune a BERT model based on the methods2test data. It's not an issue per se but I wasn't sure where to look.
Specifically, I follow the instructions from here: https://huggingface.co/docs/transformers/training
But, I cannot figure out how to use the corpus/preprocessed data for the training part:

`trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=small_train_dataset,
    eval_dataset=small_eval_dataset,
    compute_metrics=compute_metrics,
)`

When I unzip the .tar.bz2 files I get some .bin and .idx items. 
How do I use them in the train_dataset/eval_detaset from the above snippet?

**Comment by DolanDack** [comment]
Just to clarify more, my aim is to fine-tune the UniXcoder - code generation (https://github.com/microsoft/CodeBERT/tree/master/UniXcoder) by utilising the methods2test dataset.

**Comment by micheletufano** [comment]
Hi @DolanDack,

Since you plan to train a different model, I would suggest you starting from the raw corpus ([raw parallel corpus](https://github.com/microsoft/methods2test/tree/main/corpus) as strings), and then use the specific model's tokenizer (BERT tokenizer, or UniXcoder tokenizer) to preprocess the data. This is because the preprocessed data would not work well if the model you are training uses a different tokenizer/vocabulary.
